language: java

jdk:
- openjdk8

script: ./mvnw clean verify

env:
  global:
  - secure: ie8DC1FwNsp4kP5wvxTuaBrfh2LFVPihAjM7RQIdoSEoeK6jIy1T2cBNzduulTE2d/W3CO/p5LcY8RDcKgsmtVKnq8o8gnzPItQ0WjnWHiRUI/KGa9PbmnhmvCsTd6tFX7Te+1LyuBbChn2Matj+JzKd3MKGl2bPq7K9db//zWESbbUPtEu1quRX6ecn1fqJPEqwRHsSpApGOOSTVx4t5tOkzGsLszyzVcwF/PCJijuEhDntdDrSn19o7OVPkwzeZNhMKwfBQ57PTCTcrrym4r5n+RPnIc2XrM6dtwo1uo77cNYbcvhjK0ke0GzcLHituQ0XvkOa6Xu+BKYKlYFG2wSIkB4Lx6F58XXcD+uQCmwB+Hn3t19KJXsteVEOEcDo8VA2rTJsfRF3KN9ADAK30kqsQo2J2x+6/sI+eUoVfCfgzKXUn1P4cH0w1g/nXDjlRD7YVO5nOzmcmP6AvhEIbDZMcvtoVVtgdGm/24DR6ei06e1gnxagcf/tcf8Oy74zrLoIQ5t9SJEWBJTg1p6bcpFuJCUs7xuj9vp4gbota/ni3woz2/yvnQ8VOs5BKHaX0RAzF6o6LbcLok0GMb/IZ5hvSpMioyOwSgaj4348xIvsL4IYHOV3wuN3wL+DdVAOuWLzg9pxP3MMRJ25ZksNLEsMc3JGf5CxYL+EX1ijkqs=
  - secure: XZQ9hONwpjwZJ4fF/KJTTqWCB5RtABBE2U6wzeG2xGhQ43Eyyq+0rCrPT2arlGbOOylEAyvPPWzntXAJt5STY+1HR4KCWTXQZePIw3NrKv7iT00Q8hXpu9oZ4LB37wWzti1T3sKx3ntAMeWtC0G+fkzhwgIL7oi73fFuoJCyZ8HiMiXHGZlt6G4/gM2CfHIZdeE3Kq8f34xnTyBP/EdVG02Zo21NibPVV5Uqyz6yJIOsVThe3FvZ0R1S4ZKGlaQdr1tlySGxTVi6hZd61oPgPIz42SEkFBCX1YcuDS6aZOUq+Nq1tI6JP51tGkkD/hX1+QDh2zpYU0224rTrxRILyCehLLkYWhn/n5OVP7eULsRf/hU0diifE56Kqq31/ufORrRFCc5ZbsR0BEX4y4B9yvdmaW1HqCcPs54KTXgIxRDHY+PgipVITZ8zU6DVUIlQIY3RpDcMYq/sJEm/TC6M8PzSKhmfjvUqhVSJ73E7AbJVPX58jxIzJdNNFPVnC4obXn9RJ7R89oVzQm4BwbhpVSSrJUpdsPvzdgAtizdDb4gbcB83xka+sO7RlYS0PGoPXuA1gmw+lNkT+JhAcPAxrMrxtpvcgCQTLj/N9pi6pWFoenBDLT73mu5lyu/+L7DYdTLplnz08RZWx9IrcVcmdmSRxlGMhnsM2PITwWDnBks=

deploy:
  provider: script
  script: .travis-docker.sh
  on:
    repo: cy4n/hello
#    tags: true
